### PR TITLE
Add more troubleshooting steps

### PR DESCRIPTION
**Pull request by marcelstoer**
- document the jumper cable colors
- document how to install build tools
- document how to troubleshoot missing i2c permissions

### CODE REVIEW

**Review by psachs — APPROVED** [review]

**Comment by psachs** [comment]
Thank you very much for your contribution to the documentation.

**Comment by marcelstoer** [comment]
I love what you guys do: https://twitter.com/frightanic/status/1364710456754110469

It appears my changes got lost after you merged them as @MBjoern merged other stuff around the same time.

**Comment by psachs** [comment]
yes sorry about that. Since we use a internal tool to generate and test the driver we setup a mirroring from our internal git server. We will backport your contribution so it doesn't get overwritten again

**Comment by marcelstoer** [comment]
Ah, that's what it is, makes sense now. I was really puzzled when I didn't even see my 2nd PR on master.

**Pull request merged**
